name: Infra Provisioning

on:
  push:
    branches:
      - main
      - feature/**
    paths:
      - 'terraform/**'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.12.0"  # Specify your desired version.

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: github-actions-infra-plan
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Format
      run: terraform fmt -check -recursive
      working-directory: terraform

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: terraform

    # - name: Cleanup locks on cancellation
    #   if: cancelled()
    #   run: terraform force-unlock -force $(terraform show -json 2>/dev/null | jq -r '.lock_id // empty') || true
    #   working-directory: terraform
    #   continue-on-error: true  

    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform